import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { trpc } from "../utils/trpc";
import ProductCard from "../components/UI/ProductCard";
import { useEffect } from "react";
import useProductStore from "../stores/productStore";
const Home: NextPage = () => {
  const [products, setProducts] = useProductStore(({ products, setProducts }) => [products, setProducts])
  const { data: productsFromServer, error, isLoading } = trpc.products.getAllProducts.useQuery(undefined, { retry: false });
  useEffect(() => {
    setProducts(productsFromServer ?? [])
  }, [productsFromServer])
  if (error?.message) {
    return <div>{error.message}</div>
  }

  return (
    <>

      <Head>
        <title>Techzone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="flex gap-3 flex-wrap  justify-center" >
          {
            isLoading && <div className="h-screen flex items-center justify-center" >
              <span className="loading loading-ring loading-lg scale-150"></span>
            </div>
          }
          {products?.map((product) => {

            return <div key={product.pid} >
              <ProductCard props={product} />
            </div>
          })
          }
        </div>
      </main>

    </>
  );
};
export default Home;